### ISSUE TITLE
More accurate prices

### ISSUE THREAD

**Issue by OceanManOne** [almatrass/vgo-trade-site#2]
Hello,

I've gone through the code and saw that the prices shown in the website are coming from the "suggested_price" field of the opskins api (before changing them to fit the ratings).

Comparing to the other vgo trading websites such as skinsjar is showing that the prices on some items are not even close, which raise the question: how does skinsjar get its prices.

Going through opskins it seems skinsjar prices are really close the the actual prices of the items sold on opskins (which will be my guess of how they calculating their prices).

I've looked through opskins api but couldn't found any way to get data on the **vgo** items prices on the website. Do you think there is a possible way to get more accurate prices than the suggested ones?

PS Great job on the website!

**Comment by almatrass** [comment]
Hey!

I've had a look through the documentation, and there is an API endpoint here for suggested prices:
https://api.opskins.com/IPricing/GetSuggestedPrices/v2/?appid=1912
OPSkins' suggested prices in the item object are the `op_7_day` values from that endpoint.

However for calculating averages based on sales, SkinsJar are most likely using this endpoint with a full detailed list of sales:
https://api.opskins.com/IPricing/GetPriceList/v2/?appid=1912

I didn't look into this one too much, but at a glance SkinsJar prices are very similar to an average of the daily average prices from that endpoint. 

I don't know how big a role the actual sales have on the OPSkins suggested prices, I would assume quite a bit, but at the same time they probably have more protection against market manipulation scams.

If you do use this endpoint, you'll have to take the manipulation scams into account when making the price tracker, but as the main point of this project is really meant to just be an example of ExpressTrade, I probably won't add this tracking to this script.

Good luck!
